services:
  api:
    # Constrói a imagem a partir do Dockerfile no diretório atual ('.')
    build: .
    # Mapeia a porta 8000 do host para a porta 8000 do contêiner.
    container_name: imersao-devops # Nome do container
    ports:
      - "8000:8000"
    # Monta o diretório atual do host no diretório /app do contêiner.
    # Isso permite o hot-reloading e a persistência do banco de dados SQLite.
    volumes:
      - .:/app
    # Comando para iniciar a aplicação com uvicorn.
    # --host 0.0.0.0 é necessário para que a API seja acessível de fora do contêiner.
    # --reload reinicia o servidor automaticamente quando há alterações no código.
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload